import { Link } from 'react-router-dom';
import Seo from '../components/Seo';
import { ArrowRight, Check } from '../components/Icons';
import { pageMeta } from '../config';

const cases = [
  { no: '01', title: 'Ремонт техники', source: 'Отзывы о сервисе и трёх конкурентах', signal: 'Клиенты готовы принять перенос срока, если узнают о нём заранее. Негатив возникает, когда обещанная дата проходит, а статус приходится выяснять самостоятельно.', evidence: ['«Срок перенесли, но никто не предупредил»', '«Три дня звонил, чтобы узнать статус»', 'У конкурентов отдельно хвалят сообщения о ходе ремонта'], wrong: 'Ускорять все ремонты любой ценой. В отзывах проблема не в каждом сроке, а в отсутствии понятной коммуникации.', actions: ['Сообщать об изменении срока до звонка клиента', 'Дать простой способ проверить статус', 'Согласовывать новый срок и фиксировать его в сообщении'] },
  { no: '02', title: 'Товар на маркетплейсе', source: 'Отзывы о товаре и аналогах в категории', signal: 'Часть низких оценок связана не с качеством товара, а с повреждённой упаковкой, непонятной комплектацией и сложным первым запуском.', evidence: ['«Не понял, какой переходник нужен»', '«Коробка пришла мятая, товар работает»', 'У лидера категории чаще хвалят инструкцию с фотографиями'], wrong: 'Переделывать сам продукт на основании всего массива негатива. Сначала нужно отделить продукт от доставки и неверных ожиданий.', actions: ['Показать комплектацию крупным планом', 'Добавить инструкцию первого запуска на одну страницу', 'Разделить обращения о товаре, упаковке и доставке'] },
  { no: '03', title: 'Клининговый сервис', source: 'Отзывы о заказах и локальных конкурентах', signal: 'Клиенты описывают совершенно разный уровень результата. Сильных исполнителей рекомендуют по имени, но общий стандарт бренда остаётся непредсказуемым.', evidence: ['«В прошлый раз было идеально, сейчас пришлось переделывать»', '«Заказываю только конкретного специалиста»', 'У конкурента чаще отмечают проверку результата до ухода исполнителя'], wrong: 'Считать проблему отдельными ошибками сотрудников. Для клиента каждый исполнитель представляет весь сервис.', actions: ['Ввести короткий чек-лист результата', 'Проверять критичные зоны до завершения заказа', 'Фиксировать предпочтения клиента и обратную связь по исполнителю'] },
];

export default function Cases() {
  return <>
    <Seo {...pageMeta.cases} path="/cases" />
    <section className="page-hero"><div className="container narrow"><div className="eyebrow">Примеры выводов</div><h1>Вот что значит «перевести отзывы в решение».</h1><p>Сначала — реальный экспресс-разбор открытых отзывов. Ниже — дополнительные демонстрационные ситуации без выдуманных процентов роста.</p></div></section>
    <section className="real-case-section"><div className="container real-case-grid">
      <div className="real-case-intro"><span className="real-case-label">Реальный пример · открытые данные</span><h2>Весь вывод — на одной странице</h2><p>Один главный сигнал, три подтверждения и первое действие. Отчёт можно понять примерно за минуту. Это независимый пример работы, а не заказ или одобрение со стороны компании.</p><div className="real-case-actions"><a className="btn btn-primary" href="/materials/real-review-analysis-cleanbros.pdf" target="_blank" rel="noreferrer">Открыть 1 страницу <ArrowRight /></a><Link className="btn btn-secondary" to="/audit">Получить разбор своих отзывов</Link></div></div>
      <div className="real-case-result"><div><span>Главный сигнал</span><strong>Обещанный состав заказа и фактическое исполнение иногда расходятся.</strong></div><div><span>Почему это важно</span><p>Тогда претензия относится не только к уборке, но и к доверию к приложению, чек-листу и бренду.</p></div><div><span>Первое изменение</span><p>За 24 часа подтверждать состав работ, команду, инвентарь и контакт для быстрой эскалации.</p></div><div className="real-case-source"><span>Основание</span><p>Публичные отзывы на четырёх карточках Яндекс Карт, 2024–2026 годы. Выводы — гипотезы для проверки, а не утверждения о внутренних процессах.</p></div></div>
    </div></section>
    <section className="section"><div className="container case-detail-list">{cases.map(item => <article className="case-detail" key={item.no}><header className="case-detail-head"><span className="case-number">{item.no}</span><div><span className="demo-banner">Демонстрационный кейс</span><h2>{item.title}</h2><p>{item.source}</p></div></header><div className="case-signal"><span>Главный вывод</span><p>{item.signal}</p></div><div className="case-analysis"><div><h3>На чём основан вывод</h3>{item.evidence.map(x => <p className="mini-check" key={x}><Check />{x}</p>)}</div><div className="why-card"><span>Не делать</span><p>{item.wrong}</p></div><div><h3>Что проверить первым</h3>{item.actions.map((x, i) => <p className="action-row" key={x}><span>0{i + 1}</span>{x}</p>)}</div></div></article>)}</div></section>
    <section className="cta-band"><div className="container split-copy"><div><div className="eyebrow light">Теперь о вашем бизнесе</div><h2>Покажу первые три сигнала в ваших отзывах.</h2></div><div><p>Пришлите ссылку на компанию, услугу или товар. Первичный разбор — 0 ₽.</p><Link className="btn btn-light" to="/audit">Получить разбор <ArrowRight /></Link></div></div></section>
  </>;
}
