import { Link } from 'react-router-dom';
import Section from '../components/Section';
import Seo from '../components/Seo';
import { ArrowRight, Check } from '../components/Icons';
import { pageMeta } from '../config';

const signals = ['Повторяющиеся жалобы', 'Причины недовольства', 'Сильные стороны', 'Проблемы сервиса', 'Проблемы продукта', 'Ожидания клиентов', 'Конкурентные ориентиры', 'Зоны первой проверки'];
const cases = [
  ['01', 'Сервис ремонта компьютеров', '284 отзыва', 'Коммуникация, сроки и прозрачность стоимости'],
  ['02', 'Товар на маркетплейсе', '812 отзывов', 'Продукт, ожидания, доставка и первый запуск'],
  ['03', 'Клининговый сервис', '356 отзывов', 'Стандарты качества, опоздания и повторные заказы'],
];

export default function Home() {
  return <>
    <Seo {...pageMeta.home} path="/" />
    <section className="hero"><div className="container hero-grid">
      <div className="hero-copy"><div className="eyebrow">Аналитика клиентской обратной связи</div><h1>Находим закономерности в отзывах и превращаем их в решения для бизнеса</h1><p className="hero-lead">Анализируем клиентскую обратную связь, выделяем повторяющиеся проблемы и показываем, что стоит исправить в первую очередь.</p><div className="hero-actions"><Link className="btn btn-primary" to="/cases">Посмотреть примеры анализа <ArrowRight /></Link><Link className="btn btn-secondary" to="/audit">Запросить первичный разбор</Link></div></div>
      <aside className="analysis-preview" aria-label="Демонстрационный фрагмент анализа"><div className="preview-top"><span>Фрагмент анализа</span><span className="demo-label">Демонстрационный пример</span></div><p className="preview-kicker">Сервис ремонта · 284 отзыва</p><h2>Статус заказа важнее самой задержки</h2><div className="priority-row"><span>Частота</span><div className="track"><i style={{ width: '72%' }} /></div><b>Высокая</b></div><div className="priority-row"><span>Влияние</span><div className="track"><i style={{ width: '86%' }} /></div><b>Высокое</b></div><div className="insight-note"><span>Вывод</span><p>Неопределённость усиливает недовольство. Уведомление при изменении срока — действие первой очереди.</p></div></aside>
    </div></section>
    <section className="logic"><div className="container logic-row">{['Отзывы', 'Закономерности', 'Приоритеты', 'Решения'].map((item, i) => <div key={item}><span>0{i + 1}</span><strong>{item}</strong>{i < 3 && <ArrowRight />}</div>)}</div></section>
    <Section eyebrow="Что можно увидеть" title="Клиенты уже описывают, где бизнес работает хорошо, а где возникает трение." intro="Задача анализа — собрать отдельные впечатления в общую картину и не принять единичный случай за систему."><div className="signal-grid">{signals.map((signal, i) => <div key={signal}><span>0{i + 1}</span><p>{signal}</p></div>)}</div></Section>
    <Section eyebrow="Как строится работа" title="От массива отзывов — к ясной очередности действий." className="section-tinted"><div className="method-preview"><div><span>01</span><h3>Структурируем</h3><p>Приводим обратную связь к удобному виду и отделяем технический шум.</p></div><div><span>02</span><h3>Сопоставляем</h3><p>Ищем повторяющиеся темы, контекст, серьёзность и сильные стороны.</p></div><div><span>03</span><h3>Расставляем приоритеты</h3><p>Показываем, что проверить первым и почему это важно для клиента.</p></div></div><Link className="text-link" to="/method">Посмотреть методику <ArrowRight /></Link></Section>
    <Section eyebrow="Конкурентный контекст" title="Смотрим не только на ваш бизнес, но и на ожидания клиентов в категории."><div className="competitive-grid"><div className="competitive-intro"><p>По согласованным конкурентам анализируем открытые отзывы и сравниваем, какие темы повторяются у всех, а где конкретный бизнес заметно выигрывает или уступает.</p><p>Сильные практики конкурентов не копируются механически. Мы разбираем, почему клиенты их ценят, и предлагаем, как адаптировать этот опыт под процессы и возможности вашего бизнеса.</p></div><div className="competitive-points"><div><span>01</span><h3>Находим ориентиры</h3><p>Что клиенты особенно ценят у сильных игроков рынка.</p></div><div><span>02</span><h3>Видим разрывы</h3><p>Где ожидания клиентов уже выше привычного уровня вашего сервиса.</p></div><div><span>03</span><h3>Переводим в действия</h3><p>Какие практики стоит проверить, адаптировать и внедрить в первую очередь.</p></div></div></div></Section>
    <Section eyebrow="Примеры анализа" title="Демонстрационные кейсы показывают формат и глубину работы." intro="На примерах видно, как устроен анализ, расставляются приоритеты и формируются рекомендации."><div className="case-preview-grid">{cases.map(([no, title, amount, text]) => <Link to="/cases" className="case-preview" key={no}><div><span className="case-no">{no}</span><span className="demo-label">Демонстрационный кейс</span></div><h3>{title}</h3><p>{text}</p><strong>{amount} <ArrowRight /></strong></Link>)}</div></Section>
    <section className="data-section"><div className="container split-copy"><div><div className="eyebrow light">Качество данных</div><h2>Не все отзывы одинаково полезны для выводов.</h2></div><div><p>Подробное описание конкретной ситуации даёт больше информации, чем короткое «Всё отлично». Мы оцениваем содержательность, конкретику, повторяемость и необычную однородность формулировок.</p><p>Это не попытка объявить отдельный отзыв купленным. Цель — не принять шум за реальный голос клиента.</p><Link className="btn btn-light" to="/method">Как оцениваются отзывы</Link></div></div></section>
    <Section eyebrow="Об аналитике" title="Понятные выводы вместо отчёта ради отчёта."><div className="about-row"><p>Работа строится вокруг структурирования обратной связи, поиска устойчивых закономерностей и перевода наблюдений в конкретные бизнес-рекомендации.</p><div>{['Без вымышленных результатов', 'Без технологического жаргона', 'С объяснением логики приоритета'].map(x => <span key={x}><Check />{x}</span>)}</div></div></Section>
    <section className="cta-band"><div className="container split-copy"><div><div className="eyebrow light">Первичный разбор</div><h2>Начните с нескольких закономерностей в своих отзывах.</h2></div><div><p>Рассмотрим часть открытой обратной связи. Стоимость — 0 ₽, без обязательства заказывать полный аудит.</p><Link className="btn btn-light" to="/audit">Запросить первичный разбор <ArrowRight /></Link></div></div></section>
  </>;
}
